version: '3.8'

services:
  db:
    image: postgres:16
    container_name: dbs-postgres
    restart: always
    environment:
      POSTGRES_USER: dbs-erp-user
      POSTGRES_PASSWORD: dbs-erp-pass
      POSTGRES_DB: dbs-erp-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: