/* Registre du personnel et catalogue des opérations relevés dans la sauvegarde
 * DBS du 12/08/2026 (clé `dbs_gpao_prod_v2`).
 *
 * Fichier généré depuis la sauvegarde : ne pas éditer à la main.
 * Les matricules apparaissant plusieurs fois sont réduits à leur première
 * occurrence — l'unicité est une contrainte de la table. */

export type PersonneSeed = { matricule: string; nom: string; fonction: string; atelier: string; statut: string };
export type OperationSeed = { nom: string; sam: number; archive: boolean };

export const PERSONNEL_DBS: PersonneSeed[] = [
  {"matricule": "1", "nom": "Chawechi Ida", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "2", "nom": "Khtatfi Imen", "fonction": "CLASSAGE COL + MANCHE + 0.6 FONTE", "atelier": "", "statut": "active"},
  {"matricule": "4", "nom": "Misfar Imen", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "5", "nom": "Jaar Rihab", "fonction": "SURPIQURE 0.1 MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "8", "nom": "Bouzid Leila", "fonction": "3 FIL COTE", "atelier": "", "statut": "active"},
  {"matricule": "9", "nom": "Amri Dalel", "fonction": "PIQUAGE COL + RAZEZ", "atelier": "", "statut": "active"},
  {"matricule": "11", "nom": "Daoudi Olfa", "fonction": "MONTAGE PATTE DEVANT", "atelier": "", "statut": "active"},
  {"matricule": "13", "nom": "Rezgui Roudayna", "fonction": "MARPUAGE PLIS COL", "atelier": "", "statut": "active"},
  {"matricule": "17", "nom": "Nasri Manel", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "18", "nom": "Dridi Meriem", "fonction": "SURPIQURE DOUBLURE FONTE DOS + OURLE BAS DOUBLURE", "atelier": "", "statut": "active"},
  {"matricule": "26", "nom": "Mhedhbi Khouloud", "fonction": "OURLE MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "27", "nom": "Ghzela Imen", "fonction": "MONTAGE PLIS + FIXATION TIKE GREFFE", "atelier": "", "statut": "active"},
  {"matricule": "29", "nom": "Jaar Sondes", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "30", "nom": "Ben salem Ameni", "fonction": "MONTAGE MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "31", "nom": "Challouf Nassira", "fonction": "MONTAGE COL", "atelier": "", "statut": "active"},
  {"matricule": "32", "nom": "Ben salem Awatef", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "35", "nom": "Frija Latifa", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "36", "nom": "Maatoug Houda", "fonction": "POIGNET CONDUITECH", "atelier": "", "statut": "active"},
  {"matricule": "38", "nom": "Rezgui Samiha", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "39", "nom": "Daoudi Monjia", "fonction": "3 FIL COTE", "atelier": "", "statut": "active"},
  {"matricule": "40", "nom": "Rezgui Imen", "fonction": "RABATTAGE COL", "atelier": "", "statut": "active"},
  {"matricule": "41", "nom": "Azouizi Selma", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "43", "nom": "Ben Nacer Hanen", "fonction": "OURLE BAS", "atelier": "", "statut": "active"},
  {"matricule": "44", "nom": "Ayechi Amira", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "45", "nom": "El Whichi Aida", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "46", "nom": "Briki Fodha", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "47", "nom": "Ben salem Leila", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "48", "nom": "Boudrogua Hnya", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "49", "nom": "Frija Hayet", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "50", "nom": "Bellahirech Rihab", "fonction": "COUTOUR ANGLAISE COTE + MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "51", "nom": "Ziedi Siwar", "fonction": "ASSEMBLLAGE EPAUL", "atelier": "", "statut": "active"},
  {"matricule": "52", "nom": "Ben salem Khouloud", "fonction": "NERVURE COL", "atelier": "", "statut": "active"},
  {"matricule": "54", "nom": "Hmidi Soumaya", "fonction": "RABATAGE PATTE MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "55", "nom": "Rezgui Nabila", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "56", "nom": "Yezidi Hamida", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "57", "nom": "Zardoum Amina", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "58", "nom": "Bouden Afifa", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "60", "nom": "Chatteli Mouna", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "61", "nom": "Dridi Saliha", "fonction": "ASSEMBLLAGE PIED DE COL", "atelier": "", "statut": "active"},
  {"matricule": "62", "nom": "Maamar Houda", "fonction": "CLASSAGE MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "63", "nom": "El Yahbi Souad", "fonction": "3 FIL MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "65", "nom": "Souidi Saiida", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "66", "nom": "Trabelsi Amel", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "67", "nom": "Yahbi Sameh", "fonction": "REPASSAGE PATTE DEVANT", "atelier": "", "statut": "active"},
  {"matricule": "69", "nom": "El Whichi Tayssir", "fonction": "SURPIQURE 0.5 MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "70", "nom": "Ben Salem Hourya", "fonction": "MONTAGE MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "71", "nom": "Moussi Neila", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "72", "nom": "Hmidi Amira", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "73", "nom": "Baraket Sabeh", "fonction": "MONTAGE MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "76", "nom": "Bourchada Raouia", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "78", "nom": "Khtatfi Asma", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "80", "nom": "Ben Hssin Sarra", "fonction": "SURPIQURE 0.1 MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "81", "nom": "Maroueni Khalil", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "83", "nom": "Jamel Eddin Chourouk", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "86", "nom": "Ben Salem Kaouthar", "fonction": "SURPIQURE 0.1 MANCHE + VOULANT", "atelier": "", "statut": "active"},
  {"matricule": "87", "nom": "Brik Zohra", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "97", "nom": "Slouma Sondes", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "101", "nom": "Karzout Yosra", "fonction": "FRONCE TETE + BAS MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "109", "nom": "Feki Achraf", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "115", "nom": "El Whichi Mounira", "fonction": "MONTAGE COL", "atelier": "", "statut": "active"},
  {"matricule": "120", "nom": "Souissi Amira", "fonction": "MONTAGE PATTE + BIAIS MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "121", "nom": "Bourbia Salma", "fonction": "FRONCE DEVANT + DOS", "atelier": "", "statut": "active"},
  {"matricule": "123", "nom": "Ben Othmen Meriem", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "129", "nom": "Baraket Saloua", "fonction": "OURLE BAS VOULANT", "atelier": "", "statut": "active"},
  {"matricule": "130", "nom": "Gorrab Thouraya", "fonction": "MONTAGE MANCHE + 3 FIL COL +3 FIL MANCHE DOUBLURE", "atelier": "", "statut": "active"},
  {"matricule": "131", "nom": "Ziedi Amal", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "133", "nom": "Boudrigua Sabrine", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "142", "nom": "Jlassi Hana", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "144", "nom": "Ben Rhouma Rim", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "145", "nom": "Laouini Houda", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "151", "nom": "Baccar Nahed", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "152", "nom": "Ben Hayej Ikram", "fonction": "SURPIQURE 0.6 DOS + EPAUL + POSE COMPOSITION + COTE", "atelier": "", "statut": "active"},
  {"matricule": "153", "nom": "Omar Dorsaf", "fonction": "FRONCE BAS MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "154", "nom": "Mezni Moufida", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "157", "nom": "Manaii Saiida", "fonction": "FRONCE DOS + EPAUL", "atelier": "", "statut": "active"},
  {"matricule": "162", "nom": "Zirda Soumaya", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "163", "nom": "Hayouni Hamida", "fonction": "SURPIQURE 0.1 MANCHE", "atelier": "", "statut": "active"},
  {"matricule": "167", "nom": "Chabbouh Imen", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "168", "nom": "Trabelsi Najla", "fonction": "RABATTAGE COL + POSE GREFFE", "atelier": "", "statut": "active"},
  {"matricule": "169", "nom": "Bel Hadj Fakher", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "170", "nom": "Makhlouf Hanen", "fonction": "MONTAGE COL", "atelier": "", "statut": "active"},
  {"matricule": "171", "nom": "Manoubi Aida", "fonction": "PIQUAGE POIGNET", "atelier": "", "statut": "active"},
  {"matricule": "172", "nom": "Ahmad Zohra", "fonction": "3 FIL DOUBLURE DOS + EPAUL + COTE", "atelier": "", "statut": "active"},
  {"matricule": "176", "nom": "Abouda Imen", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "178", "nom": "Zirda Ranim", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "179", "nom": "Ben Salem Hassiba", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "181", "nom": "Fkiri Moufida", "fonction": "MONTAGE MANCHEE", "atelier": "", "statut": "active"},
  {"matricule": "182", "nom": "Ziedi Lamia", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "183", "nom": "Hmidi Rabiaa", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "184", "nom": "Dhifallah Dorsaf", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "185", "nom": "Ben Salha Lina", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "186", "nom": "Gorrab Najeh", "fonction": "MONTAGE PATTE DEVANT", "atelier": "", "statut": "active"},
  {"matricule": "187", "nom": "Laouiti Manel", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "188", "nom": "Marad Soumaya", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "190", "nom": "Ghdir Dalinda", "fonction": "NERVURE EMPIECEMENT + ASSEMBLLAGE EPAUL +NERURE", "atelier": "", "statut": "active"},
  {"matricule": "192", "nom": "Saied Haifa", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "193", "nom": "Ismaiil Firas", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "194", "nom": "Bouzrati Yomna", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "195", "nom": "Chtiwi Yassin", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "196", "nom": "Ben salem Fadia", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "197", "nom": "Mrad Ahlem", "fonction": "ASSEMBLLAGE EMPIECEMENT", "atelier": "", "statut": "active"},
  {"matricule": "198", "nom": "Mhamdi Fathia", "fonction": "PIQUAGE POIGNET", "atelier": "", "statut": "active"},
  {"matricule": "199", "nom": "Feki Rafika", "fonction": "", "atelier": "", "statut": "active"},
  {"matricule": "200", "nom": "Dridi Chahra", "fonction": "COUTOUR ANGLAISE COTE", "atelier": "", "statut": "active"},
  {"matricule": "106", "nom": "Darra Dorai", "fonction": "MONTAGE PLIS + FIXATION PASSANT + ASSEMBLLAGE EMPIECEMENT", "atelier": "", "statut": "active"},
  {"matricule": "107", "nom": "Sarra Dorai", "fonction": "MONTAGE PLIS + FIXATION PASSENT + ASSEMBLLAGE EMPIECEMENT", "atelier": "", "statut": "active"},
  {"matricule": "108", "nom": "Hbiba Ben Amar", "fonction": "PIQUAGE POCHE", "atelier": "", "statut": "active"},
  {"matricule": "110", "nom": "Becheikh  Ahlem", "fonction": "MONTAGE COL", "atelier": "", "statut": "active"},
];

export const OPERATIONS_DBS: OperationSeed[] = [
  {"nom": "CLASSAGE + MONTAGE COL + RABATTAGE", "sam": 210, "archive": false},
  {"nom": "BOND DE TAILLE", "sam": 170, "archive": false},
  {"nom": "MONTAGE DOUBLURE TAILLE", "sam": 170, "archive": false},
  {"nom": "FIXATION LASTIK +SURPIQURE TAILLE", "sam": 170, "archive": false},
  {"nom": "3 FIL MANCHE", "sam": 130, "archive": false},
  {"nom": "OURLE FONTE DOUBLURE", "sam": 160, "archive": false},
  {"nom": "ASSEMBLLAGE JOUPE DOUBLURE A BISTIER + NERVURE MORTE", "sam": 250, "archive": false},
  {"nom": "SURPIQURE TAILLE", "sam": 190, "archive": false},
  {"nom": "FRONCE VOULANT", "sam": 160, "archive": false},
  {"nom": "ASSEMBLLAGE VOULANT", "sam": 260, "archive": false},
  {"nom": "OURLE BAS VOULANT", "sam": 160, "archive": false},
  {"nom": "3 FIL VOULANT DOUBEL", "sam": 190, "archive": false},
  {"nom": "PREPARATION PIED DE COL + NERVURE", "sam": 100, "archive": false},
  {"nom": "ASSEMBLLAGE EPAUL", "sam": 100, "archive": false},
  {"nom": "SURPIQURE EPAUL +  COL", "sam": 10, "archive": false},
  {"nom": "OURLE BAS DEVANT + DOS", "sam": 170, "archive": false},
  {"nom": "MONTAGE PATTE + BIAIS MANCHE", "sam": 150, "archive": false},
  {"nom": "RABATTAGE PATTE MANCHE", "sam": 150, "archive": false},
  {"nom": "SURPIQURE MANCHE + POSE GREFFE", "sam": 130, "archive": false},
  {"nom": "ASSEMBLLAGE COTE", "sam": 160, "archive": false},
  {"nom": "POSE COMPOSITION + SURPIQURE COTE", "sam": 180, "archive": false},
  {"nom": "POIGNET CONDUITECH", "sam": 160, "archive": false},
  {"nom": "SURPIQURE 0.5 POIGNET", "sam": 150, "archive": false},
  {"nom": "RABATTAGE COL", "sam": 120, "archive": false},
  {"nom": "MONTAGE COL", "sam": 130, "archive": false},
  {"nom": "MONTAGE PLIS MANCHE", "sam": 95, "archive": false},
  {"nom": "PIQUAGE POIGNET", "sam": 130, "archive": false},
  {"nom": "3 FIL DEVANT", "sam": 65, "archive": false},
  {"nom": "3 FIL DOS + BAS", "sam": 100, "archive": false},
  {"nom": "3 FIL EPAUL + COTE + MANCHE", "sam": 100, "archive": false},
  {"nom": "SURPIQURE 0.6 DOS + EPAUL + COTE + MANCHE", "sam": 100, "archive": false},
  {"nom": "BIAIS MANCHE", "sam": 100, "archive": false},
  {"nom": "MARQUAGE + FIXATION ELASTIQUE + NERVURE COL", "sam": 100, "archive": false},
  {"nom": "PIQUAGE COL", "sam": 100, "archive": false},
  {"nom": "MARQUAGE + FIXATION ELASTIQUE POIGNET", "sam": 215, "archive": false},
  {"nom": "CHLASSAGE DOUBLURE DOS + ASSEMBLLAGE EMPIECEMENT", "sam": 160, "archive": false},
  {"nom": "CHASSAGE DOUBLURE DEVANT", "sam": 140, "archive": false},
  {"nom": "FRONCE MANCHE + FRONCE VOULANT", "sam": 100, "archive": false},
  {"nom": "ASSEMBLLAGE PATTE + NERVURE + BIAIS MANCHE +PREPARACIENT EPAUL", "sam": 279, "archive": false},
  {"nom": "MONTAGE PATTE DEVANT", "sam": 180, "archive": false},
  {"nom": "RABATTAGE PATTE DEVANT", "sam": 130, "archive": false},
  {"nom": "3 FIL COTE DOUBLURE + COTE + VOULANT", "sam": 85, "archive": false},
  {"nom": "COUTUR ONGLAISE COTE + VOULANT", "sam": 90, "archive": false},
  {"nom": "A2SSEMBLLAGE COL + NERVURE", "sam": 105, "archive": false},
  {"nom": "SURPIQURE 0.5 DOUBLURE COTE + CLASSAGE MANCHE + FIXATION LAIN", "sam": 175, "archive": false},
  {"nom": "3 FIL DOUBLURE COTE + MANCHE", "sam": 190, "archive": false},
  {"nom": "COUTOUR ANGLAISE COTE + PSE COMPOCECIENT + 0.1 MANCHE", "sam": 145, "archive": false},
  {"nom": "ASSEMBLLAGE VOULONT TAILLE", "sam": 170, "archive": false},
  {"nom": "3 FIL VOULANT + MANCHE", "sam": 87, "archive": false},
  {"nom": "COUTOUR ANGLAISE VOULANT + MANCHE", "sam": 130, "archive": false},
  {"nom": "3 FIL VOULANT", "sam": 50, "archive": false},
  {"nom": "COUTOUR ANGLAISE VOULANT", "sam": 130, "archive": false},
  {"nom": "FRONCE TETE ET BAS", "sam": 160, "archive": false},
  {"nom": "FRONCE EPAUL", "sam": 28, "archive": false},
  {"nom": "BAIS MANCHE", "sam": 28, "archive": false},
  {"nom": "FRONCE MANCHE + BIAIS MANCHE", "sam": 28, "archive": false},
  {"nom": "3 FIL DOUBLURE COTE", "sam": 65, "archive": false},
  {"nom": "3 FIL FOULANT", "sam": 28, "archive": false},
  {"nom": "RAZEZ", "sam": 40, "archive": false},
  {"nom": "EPARATION PIED DE COL + RAZEZ", "sam": 70, "archive": false},
  {"nom": "PIQUAGE COL + PREPARATION PIED DE COL + RAZEZ", "sam": 70, "archive": false},
  {"nom": "AZEZ", "sam": 40, "archive": false},
  {"nom": "RATION PIED DE COL + RAZEZ", "sam": 70, "archive": false},
  {"nom": "ERVURE", "sam": 35, "archive": false},
  {"nom": "NERVURE", "sam": 35, "archive": false},
  {"nom": "MONTAGE  + RABATTAGE COL", "sam": 110, "archive": false},
  {"nom": "REPARACIENT EPAUL", "sam": 84, "archive": false},
  {"nom": "0.1 MANCHE", "sam": 80, "archive": false},
  {"nom": "ASASMBLLAGE EPAUL", "sam": 90, "archive": false},
  {"nom": "MANCHE", "sam": 125, "archive": false},
  {"nom": "RONCE VOULANT", "sam": 145, "archive": false},
  {"nom": "BIAIS MANCHE +PREPARACIENT EPAUL", "sam": 75, "archive": false},
  {"nom": "ASSEMBLLAGE PATTE", "sam": 84, "archive": false},
  {"nom": "3 FIL COULANT", "sam": 50, "archive": false},
  {"nom": "VOULANT", "sam": 100, "archive": false},
  {"nom": "FIXATION LAIN", "sam": 70, "archive": false},
  {"nom": "ASSAGE MANCHE + FIXATION LAIN", "sam": 70, "archive": false},
  {"nom": "FFIXATION LAIN", "sam": 70, "archive": false},
  {"nom": "ASSEMBLLAGE OULONT TAILLE", "sam": 170, "archive": false},
  {"nom": "PREPARASIENT EPAUL", "sam": 80, "archive": false},
  {"nom": "3 FILMANCHE", "sam": 37, "archive": false},
  {"nom": "PREPARATION PIED DE COL + RAZEZ", "sam": 55, "archive": false},
  {"nom": "SURPIQURE 0.5", "sam": 70, "archive": false},
  {"nom": "ASSEMBLLAGE+ SURPIQURE 0.5 EPAUL", "sam": 90, "archive": false},
  {"nom": "SURPIQURE 0.5 EPAUL", "sam": 70, "archive": false},
  {"nom": "OURLE BAS DOS", "sam": 60, "archive": false},
  {"nom": "OURLE BAS DEVANT", "sam": 80, "archive": false},
  {"nom": "PIQUAGE POIGNET + PREPARACENT EPAUL", "sam": 140, "archive": false},
  {"nom": "PREPARACENT EPAUL", "sam": 160, "archive": false},
  {"nom": "COUTOUR ANGLAISE COTE + VOULANT", "sam": 200, "archive": false},
  {"nom": "ASSEMBLLAGE PATTE + NERVURE", "sam": 110, "archive": false},
  {"nom": "COUTURE VOULANT", "sam": 0, "archive": false},
  {"nom": "REPARACENT EPAUL", "sam": 55, "archive": false},
  {"nom": "PREPARACIENT EPAUL", "sam": 84, "archive": false},
  {"nom": "3FIL VOULANT", "sam": 85, "archive": false},
  {"nom": "3C FIL  VOULANT", "sam": 50, "archive": false},
  {"nom": "ASSEMBLLAGE COL", "sam": 95, "archive": false},
  {"nom": "PREPARACENT COL", "sam": 95, "archive": false},
  {"nom": "SURPIQURE 0.5 DOUBLURE  COTE", "sam": 110, "archive": false},
  {"nom": "SURPQURE 0.5 DOUBLURE COTE + CLASSAGE MANCHE + FIXATION LAIN", "sam": 110, "archive": false},
  {"nom": "CLASSAGE MANCHE + FIXATION LAIN", "sam": 70, "archive": false},
  {"nom": "ASSEMBLLAGE VOULANT TAILLE", "sam": 210, "archive": false},
  {"nom": "REPASSAGE PATTE DEVANT", "sam": 120, "archive": false},
  {"nom": "3 FIL MANCHE +SURPIQURE COTE", "sam": 198, "archive": false},
  {"nom": "PIQUAGE CO", "sam": 65, "archive": false},
  {"nom": "SURPIQURE COL", "sam": 62, "archive": false},
  {"nom": "SURPIQURE COTE", "sam": 55, "archive": false},
  {"nom": "SURPIQURE MANCH", "sam": 68, "archive": false},
  {"nom": "SURPIQURE MANCHE", "sam": 68, "archive": false},
  {"nom": "3 FIL COTE", "sam": 120, "archive": false},
  {"nom": "montage manche", "sam": 130, "archive": false},
  {"nom": "3 FIL VOULANT DEVANT + DOS", "sam": 55, "archive": false},
  {"nom": "3 FIL COTE DOUBLURE", "sam": 170, "archive": false},
  {"nom": "REPASSAGE PIED DE COL", "sam": 0, "archive": false},
  {"nom": "REPASSAGE COL + PIED DE COL + COL", "sam": 0, "archive": false},
  {"nom": "REPASSAGE PATTE CPUCIN MANCHE", "sam": 0, "archive": false},
  {"nom": "MONTAGE EPAUL", "sam": 120, "archive": false},
  {"nom": "PIQUAGE EPAUL", "sam": 65, "archive": false},
  {"nom": "REPASSAGE COL", "sam": 65, "archive": false},
  {"nom": "REPASSAGE PATTE", "sam": 90, "archive": false},
  {"nom": "FIXATION LASTIK", "sam": 100, "archive": false},
  {"nom": "PIED DE COL", "sam": 55, "archive": false},
  {"nom": "REPASSAGE COL + COL", "sam": 65, "archive": false},
  {"nom": "REPASSAGE COL IED DE COL + COL", "sam": 62, "archive": false},
  {"nom": "REPASSAGE COL DE COL + COL", "sam": 55, "archive": false},
  {"nom": "REPASSAGEE POIGNET", "sam": 95, "archive": false},
  {"nom": "REPASSAGE POGNET", "sam": 95, "archive": false},
  {"nom": "REPASSAGE POIGNET", "sam": 95, "archive": false},
  {"nom": "REPASSAG POIGNET", "sam": 90, "archive": false},
  {"nom": "SURPIQURE 0.5 COTE + POSE COMPOSITION", "sam": 175, "archive": false},
  {"nom": "RABATTGE PATTE MANCHE", "sam": 125, "archive": false},
  {"nom": "PIQUAGE POIGNET + BLIS MANCHE", "sam": 0, "archive": false},
  {"nom": "SURPIQUTRE COTE", "sam": 165, "archive": false},
  {"nom": "BLIS MANCHE", "sam": 95, "archive": false},
  {"nom": "ASSEMBLLAGE EPAEUL", "sam": 78, "archive": false},
  {"nom": "SURPIQURE 0.5 COL", "sam": 45, "archive": false},
  {"nom": "SOURPIQURE 0.5 POIGNET", "sam": 100, "archive": false},
  {"nom": "SURPIQURE COL L", "sam": 27, "archive": false},
  {"nom": "SURPIQURE COTE + POSTE COMPOCECENT", "sam": 165, "archive": false},
  {"nom": "COUTOUR ANGLAISE COTE + PSE COMPOCECIENT", "sam": 147, "archive": false},
  {"nom": "COUTOUR ANGLAISE MANCHE", "sam": 90, "archive": false},
  {"nom": "FIXATION LASTIK + SURPIQURE TAILLE", "sam": 190, "archive": false},
  {"nom": "OULANT", "sam": 26, "archive": false},
  {"nom": "FXATION LAIN", "sam": 100, "archive": false},
  {"nom": "PREPARACEIENT EPAUL", "sam": 65, "archive": false},
  {"nom": "PREPARASIONT  EPAUL", "sam": 65, "archive": false},
  {"nom": "PREPARASITION EPAUL", "sam": 65, "archive": false},
  {"nom": "SURPIQURE 0.5 POIGNET + SURPIQURE 0.5 COL", "sam": 0, "archive": false},
  {"nom": "SURPIQURE COTE + POSE COMBOSESIONT", "sam": 170, "archive": false},
  {"nom": "SURPIQURE 0.1 MANCHE + POSE GREFFE", "sam": 130, "archive": false},
  {"nom": "SURPIQURE COTE + POSE COMPOSISIENT", "sam": 170, "archive": false},
  {"nom": "PREPARASIENT TIKE", "sam": 150, "archive": false},
  {"nom": "SURPIQURE 0.5 POIGNET L", "sam": 100, "archive": false},
  {"nom": "URPIQURE 0.5 COL", "sam": 85, "archive": false},
  {"nom": "POSE GREFFE + PANT DARE MANCHE + OURLE BAS DOUBLURE", "sam": 110, "archive": false},
  {"nom": "3 FIL VOULANT DOS + DEVANT", "sam": 62, "archive": false},
  {"nom": "3 FIL COTE DOUBLURE + VOULNT", "sam": 0, "archive": false},
  {"nom": "POSE GREFFE", "sam": 0, "archive": false},
  {"nom": "OURLE BAS DOUBLURE", "sam": 150, "archive": false},
  {"nom": "ASSEMBLLAGE DOUBLURE", "sam": 320, "archive": false},
  {"nom": "PREPARATION EPAUL", "sam": 84, "archive": false},
  {"nom": "3 FIL VOULNT", "sam": 60, "archive": false},
  {"nom": "PIQUAGE COL + RAZEZ", "sam": 90, "archive": false},
  {"nom": "SURPIQURE COL + SURPIQURE POIGNET", "sam": 0, "archive": false},
  {"nom": "SURPIQURE MANCHE + POSTE GREFFE", "sam": 130, "archive": false},
  {"nom": "GOIGNET CONDUITECH", "sam": 160, "archive": false},
  {"nom": "POSE COMBOSITION + SURPIQURE COTE", "sam": 177, "archive": false},
  {"nom": "PLIS MANCHE + PIQUAGE POIGNET", "sam": 0, "archive": false},
  {"nom": "PLIS MANCHE", "sam": 95, "archive": false},
  {"nom": "+ RAZEZ", "sam": 40, "archive": false},
  {"nom": "SURPIQURE POIGNET", "sam": 100, "archive": false},
  {"nom": "RPIQURE POIGNET", "sam": 100, "archive": false},
  {"nom": "SURPIQURE EPAUL", "sam": 78, "archive": false},
  {"nom": "A2SSEMBLLAGE COL + NERVURE + POSE GREFFE + PONT DARE MANCHE", "sam": 105, "archive": false},
  {"nom": "MONTAGE PATTE", "sam": 130, "archive": false},
  {"nom": "3 FILVOULANT", "sam": 55, "archive": false},
  {"nom": "MONTAGE PATTE MANCHE", "sam": 150, "archive": false},
  {"nom": "SURPIQURE EPUL + COL", "sam": 150, "archive": false},
  {"nom": "SURPIQUR COL", "sam": 65, "archive": false},
  {"nom": "POSTE GREFFE + PONT DARE MANCHE", "sam": 130, "archive": false},
  {"nom": "FRONCE TETE ET BAS MANCHE", "sam": 160, "archive": false},
  {"nom": "POSTE GREFFE + POND DARE MANCHE", "sam": 120, "archive": false},
  {"nom": "POSE GREFFE + PONDARE DEVANT", "sam": 130, "archive": false},
  {"nom": "SURPIQURE MANCHE + PONDARE + POSE GREFFE", "sam": 170, "archive": false},
  {"nom": "3 FILDEVANT", "sam": 35, "archive": false},
  {"nom": "MONTAGE PLIS MANCHE + PREPARASTIO TIKE GREFFE", "sam": 95, "archive": false},
  {"nom": "ASSEMBLLAGE PIED DE COL + RAZEZ", "sam": 0, "archive": false},
  {"nom": "ASSEMBLLAGE PIED DE COL", "sam": 60, "archive": false},
  {"nom": "3 FIL DOS", "sam": 35, "archive": false},
  {"nom": "3 FIL BAS", "sam": 50, "archive": false},
  {"nom": "3 FIL. BAS", "sam": 50, "archive": false},
  {"nom": "SURPIQURE DOS", "sam": 28, "archive": false},
  {"nom": "SURPIQURE EPAUL + COTE", "sam": 55, "archive": false},
  {"nom": "SURPIQURE DOD", "sam": 28, "archive": false},
  {"nom": "SURPIQURE  EPAUL + COTE + MANCHE", "sam": 55, "archive": false},
  {"nom": "SURPIQURE  EPAU+ COTE", "sam": 55, "archive": false},
  {"nom": "SURPIQURE COTE + POSE COMPOSITION", "sam": 0, "archive": false},
  {"nom": "3 FIL DOS + BAS + MANCHE", "sam": 0, "archive": false},
  {"nom": "3 FIL EPAUL + COTE", "sam": 115, "archive": false},
  {"nom": "3 FIL DOUBLURE DOS+EPAUL +COTE", "sam": 130, "archive": false},
  {"nom": "SURPIQURE DOS + EPAUL + POSE COMPOSITION + COTE", "sam": 0, "archive": false},
  {"nom": "SURPIQURE DOUBLURE FONTE DOS", "sam": 210, "archive": false},
  {"nom": "CLASSAGE DOUBLURE COL + MANCHE + 0.5 FONTE", "sam": 330, "archive": false},
  {"nom": "SURPIQURE EPAUL +COTE", "sam": 55, "archive": false},
  {"nom": "SURPIQUREMANCHE", "sam": 35, "archive": false},
  {"nom": "NERVURE COL", "sam": 65, "archive": false},
  {"nom": "ERVURE COL", "sam": 65, "archive": false},
  {"nom": "SURPIQURE EPAUL + POSE COMPOSITION + COTE", "sam": 150, "archive": false},
  {"nom": "3 FIL DOUBLURE DOS + EPAUL + COTE", "sam": 100, "archive": false},
  {"nom": "SURPIQURE 0.6 DOS + EPAUL + POSE COMPOSITION + COTE", "sam": 100, "archive": false},
  {"nom": "SURPIQURE DOUBLURE FONTE DOS + OURLE BAS DOUBLURE", "sam": 100, "archive": false},
  {"nom": "CLASSAGE COL + MANCHE + 0.6 FONTE", "sam": 100, "archive": false},
  {"nom": "SURPIQURE 0.6 MANCHE", "sam": 45, "archive": false},
  {"nom": "NERVURE POIGNET", "sam": 190, "archive": false},
  {"nom": "SURPIQURE 0.1 MANCHE", "sam": 100, "archive": false},
  {"nom": "FRONCE BAS MANCHE", "sam": 100, "archive": false},
  {"nom": "MONTAGE VEZLINE POIGNET", "sam": 100, "archive": false},
  {"nom": "MONTAGE POIGNET", "sam": 0, "archive": false},
  {"nom": "MONTAGE PATTE + NERVURE", "sam": 120, "archive": false},
  {"nom": "CLASSAGE MANCHE", "sam": 0, "archive": false},
  {"nom": "RABATTAGE POIGNET", "sam": 100, "archive": false},
  {"nom": "MONTAGE PLIS + FIXATION PASSANT + ASSEMBLLAGE EMPIECEMENT", "sam": 100, "archive": false},
  {"nom": "NERVURE EMPIECEMENT + ASSEMBLLAGE EPAUL +NERURE", "sam": 100, "archive": false},
  {"nom": "MONTAGE PLIS + FIXATION PASSENT + ASSEMBLLAGE EMPIECEMENT", "sam": 100, "archive": false},
  {"nom": "NERVURE DOS + ASSEMBLLAGE EMPIECEMENT + NERVURE", "sam": 100, "archive": false},
  {"nom": "SURPIQUR E EDOS PAUL + POSE COMPOSITION + COTE", "sam": 150, "archive": false},
  {"nom": "SURPIQUR EPAUL + POSE COMPOSITION + COTE", "sam": 150, "archive": false},
  {"nom": "NERVURE DOS", "sam": 40, "archive": false},
  {"nom": "ASSEMBLLAGE EMPIECEMENT + NERVURE", "sam": 100, "archive": false},
  {"nom": "CLASSAGE COL + 0.6 FONTE", "sam": 120, "archive": false},
  {"nom": "FRONCE DEVANT + DOS", "sam": 100, "archive": false},
  {"nom": "NERVURE COL + ASSEMBLLAGE PIED DE COL", "sam": 0, "archive": false},
  {"nom": "COUTOUR ANGLAISE COTE", "sam": 0, "archive": false},
  {"nom": "FRONCE DOS + EPAUL", "sam": 100, "archive": false},
  {"nom": "FRONCE DOS", "sam": 50, "archive": false},
  {"nom": "ASSEMBLLAGE EMPIECEMENT", "sam": 100, "archive": false},
  {"nom": "ASSEMPLLAGE EMPIECEMENT", "sam": 0, "archive": false},
  {"nom": "PIED DE COL RAZEZ", "sam": 20, "archive": false},
  {"nom": "FRONCE TETE + BAS MANCHE", "sam": 110, "archive": false},
  {"nom": "POSTE GREFFE", "sam": 180, "archive": false},
  {"nom": "POSET GREFFE", "sam": 90, "archive": false},
  {"nom": "3 FIL MONCHE", "sam": 80, "archive": false},
  {"nom": "COUTOUR ANGLAISE COTE + MANCHE", "sam": 120, "archive": false},
  {"nom": "PIQUAGE POCHE", "sam": 0, "archive": false},
  {"nom": "OURLE BAS", "sam": 120, "archive": false},
  {"nom": "PIQUAGE COL RAZEZ+ RAZEZ POIGNET", "sam": 0, "archive": false},
  {"nom": "MONTAGE MANCHEE", "sam": 0, "archive": false},
  {"nom": "SURPIQURE 0.5 MANCHE", "sam": 0, "archive": false},
  {"nom": "RABATTAGE COL + POSE GREFFE", "sam": 0, "archive": false},
  {"nom": "RABATAGE PATTE MANCHE", "sam": 145, "archive": false},
  {"nom": "3 FILCOTE", "sam": 50, "archive": false},
  {"nom": "OURLE INVISIBLE", "sam": 0, "archive": false},
  {"nom": "MONTAGE PLIS + FIXATION TIKE GREFFE", "sam": 100, "archive": false},
  {"nom": "MONTAGE PIGNET", "sam": 0, "archive": false},
  {"nom": "MONTAGE + RABATTAGE POIGNET", "sam": 100, "archive": false},
  {"nom": "RAZEZ POIGNET", "sam": 30, "archive": false},
  {"nom": "COTE", "sam": 110, "archive": false},
  {"nom": "COUTURE ANGLAISE COTE  MANCHE", "sam": 110, "archive": false},
  {"nom": "COUTOUR ANGLASE MANCHE", "sam": 110, "archive": false},
  {"nom": "URPIQURE COTE", "sam": 85, "archive": false},
  {"nom": "COUTURE ANGLASE  MANCHE", "sam": 110, "archive": false},
  {"nom": "CHLASSAGE DOUBLURE DOS", "sam": 100, "archive": false},
  {"nom": "3 FIL POCHE", "sam": 70, "archive": false},
  {"nom": "COUTOUR ANGLAISEMANCHE", "sam": 115, "archive": false},
  {"nom": "RAZEZ PIED DE COL", "sam": 20, "archive": false},
  {"nom": "SURPIQURE 0.1 MANCHE + VOULANT", "sam": 100, "archive": false},
  {"nom": "3 FIL POCHE + VOULANT", "sam": 100, "archive": false},
  {"nom": "COUTURE ANGLAISE POCHE", "sam": 160, "archive": false},
  {"nom": "3 FIL MANCHE + FONTE POCHE + BAS + VOULANT + TAILLE VOULANT", "sam": 100, "archive": false},
  {"nom": "ASSEMBLLAGE POCHE", "sam": 100, "archive": false},
  {"nom": "FIXATION POCHE + 0.1 DEVANT", "sam": 100, "archive": false},
  {"nom": "3 FIL EPAUL + COTE + DEVANT", "sam": 100, "archive": false},
  {"nom": "SURPIQURE 0.1 EPAUL + COTE", "sam": 160, "archive": false},
  {"nom": "ASSEMBLLAGE VOULANT A LA TAILLE", "sam": 100, "archive": false},
  {"nom": "SURPIQURE VOULANT", "sam": 0, "archive": false},
  {"nom": "TAILLE VOULANT", "sam": 0, "archive": false},
  {"nom": "FIXATION POCHE", "sam": 0, "archive": false},
  {"nom": "0.1 DEVANT", "sam": 0, "archive": false},
  {"nom": "3 FIL EPAUL", "sam": 70, "archive": false},
  {"nom": "PIQUAGE COL + NERVURE", "sam": 100, "archive": false},
  {"nom": "RAZEZ COL +PIED DE COL", "sam": 0, "archive": false},
  {"nom": "RAZEZ COL", "sam": 30, "archive": false},
  {"nom": "3 FIL VOULANT +TAILLE VOULAT", "sam": 65, "archive": false},
  {"nom": "3 FIL BAS TAILLE", "sam": 50, "archive": false},
  {"nom": "3 FIL VOULANT +TAILLE VOULANT", "sam": 65, "archive": false},
  {"nom": "MONTAGE PATTE DOS", "sam": 0, "archive": false},
  {"nom": "3 FIL VOULANT + TAILLE DOUBLURA", "sam": 50, "archive": false},
  {"nom": "FERMETURE", "sam": 0, "archive": false},
  {"nom": "MONTAGE PATTE DUBLURE", "sam": 130, "archive": false},
  {"nom": "3 FIL PATTE + DOS +EPAUL + COTE", "sam": 300, "archive": false},
  {"nom": "SURPIQURE 0.1 DOS + EPAUL + COTE + POSE COMPOSITION", "sam": 0, "archive": false},
  {"nom": "RAZEZ DEVANT", "sam": 35, "archive": false},
  {"nom": "NERVURE COL + PIED DE COL", "sam": 0, "archive": false},
  {"nom": "SURPIQURE MANCHE + VOULANT", "sam": 45, "archive": false},
  {"nom": "3 FIL BAS VOULANT+ COTE + BAS TAILLE", "sam": 0, "archive": false},
  {"nom": "FIXATION POCHE + 0.1 DEVANT+ DOS", "sam": 100, "archive": false},
  {"nom": "FIXATION POC", "sam": 60, "archive": false},
  {"nom": "DEVANT", "sam": 20, "archive": false},
  {"nom": "DOS", "sam": 30, "archive": false},
  {"nom": "PIQUAGECOL", "sam": 100, "archive": false},
  {"nom": "3 FIL TETE + BAS VOULANT", "sam": 50, "archive": false},
  {"nom": "3 FIL PONT POCHE", "sam": 30, "archive": false},
  {"nom": "0.1 DEVANT+ DOS", "sam": 70, "archive": false},
  {"nom": "3 FIL MANCHE + BAS MANCHE", "sam": 0, "archive": false},
  {"nom": "3 FIL MANCHE + BAS TAILLE", "sam": 0, "archive": false},
  {"nom": "3 FIL BAS MANCHE", "sam": 0, "archive": false},
  {"nom": "FRONCE TETE LANCHE", "sam": 0, "archive": false},
  {"nom": "OURLE MANCHE", "sam": 160, "archive": false},
  {"nom": "PIQUAGE PIED DE COL", "sam": 40, "archive": false},
  {"nom": "3 FIL VOULANT COTE", "sam": 30, "archive": false},
  {"nom": "3 FIL BAS VOULANT", "sam": 50, "archive": false},
  {"nom": "3 FIL PON POCHE", "sam": 20, "archive": false},
  {"nom": "3 FIL PON PCHE", "sam": 20, "archive": false},
  {"nom": "3 FIL MANCHE + BAS", "sam": 100, "archive": false},
  {"nom": "PAN DARE MANCHE + POSE GREFFE", "sam": 0, "archive": false},
  {"nom": "3 FIL MANCHE +BAS TAILLE", "sam": 110, "archive": false},
  {"nom": "3 FIL DOS+ EPAUL +COTE", "sam": 0, "archive": false},
  {"nom": "SURPIQURE DOS + EPAUL + COTE + POSE COMPOSITION + OURLE BAS", "sam": 0, "archive": false},
  {"nom": "3 FIL TETE+BAS VOULANT+ COTE + BAS TAILLE", "sam": 50, "archive": false},
  {"nom": "0.1 DOS", "sam": 30, "archive": false},
  {"nom": "RAZEZPIED DE COL", "sam": 20, "archive": false},
  {"nom": "NERVURE EMPIECEMENT", "sam": 100, "archive": false},
  {"nom": "POSE GREFFE + PANT DARE MANCHE", "sam": 100, "archive": false},
  {"nom": "ASSEMBLLAGE EPAUL + NERVURE", "sam": 190, "archive": false},
  {"nom": "3 FILPAN POCHE", "sam": 20, "archive": false},
  {"nom": "OURLE VOULANT", "sam": 160, "archive": false},
  {"nom": "OURLE FOULANT", "sam": 160, "archive": false},
  {"nom": "MONTAGE MANCHE + 3 FIL COTE", "sam": 0, "archive": false},
  {"nom": "RAZEZ PED DE COL", "sam": 20, "archive": false},
  {"nom": "MONTAGE COL DOUBLURE +0.1 MANCHE", "sam": 0, "archive": false},
  {"nom": "MONTAGE MANCHE + 3 FIL COL +3 FIL MANCHE DOUBLURE", "sam": 0, "archive": false},
  {"nom": "SURPIQURE 0.1 MANCHE + OURLE BAS", "sam": 0, "archive": false},
  {"nom": "RAZEZ BIED DE COL", "sam": 20, "archive": false},
  {"nom": "ASSEMBLLAGE DOUBLLURE DOS", "sam": 0, "archive": false},
  {"nom": "3 FIL. PAN POCHE", "sam": 20, "archive": false},
  {"nom": "PLIS + FIXATION PASSENT", "sam": 65, "archive": false},
  {"nom": "3 FIL MANCHE   BAS TAILLE", "sam": 60, "archive": false},
  {"nom": "3 FILMANCHE  BAS TAILLE", "sam": 60, "archive": false},
  {"nom": "3 FIL MANCHE ET BAS", "sam": 60, "archive": false},
  {"nom": "3 FIL COL", "sam": 70, "archive": false},
  {"nom": "3 FIL MANCHE DOUBLURE", "sam": 50, "archive": false},
  {"nom": "FRONCE MANCHE DOUBLURE", "sam": 120, "archive": false},
  {"nom": "RAZEZ PIED DE  COLL", "sam": 20, "archive": false},
  {"nom": "RAZEZ DOS", "sam": 30, "archive": false},
  {"nom": "3 FIL PAN POCHE", "sam": 20, "archive": false},
  {"nom": "0.1  EPAUL + DEVANT", "sam": 0, "archive": false},
  {"nom": "COUTUR ONGLAISE COTE", "sam": 0, "archive": false},
  {"nom": "3 FIL COTE + MANCHE", "sam": 100, "archive": false},
  {"nom": "COUTUR ONGLAISE COTE + MANCHE", "sam": 100, "archive": false},
  {"nom": "3 FIL DOS + DEVANT", "sam": 35, "archive": false},
  {"nom": "3 FIL  DEVANT + DOS", "sam": 60, "archive": false},
  {"nom": "PIQUAGE COL + RAZEEZ PIED DE COL", "sam": 0, "archive": false},
  {"nom": "RAZEEZ PIED DE COL", "sam": 20, "archive": false},
  {"nom": "3 FIL COL + MONTAGE MANCHE", "sam": 210, "archive": false},
  {"nom": "POSE GREFFE + PON DARE COTE", "sam": 0, "archive": false},
  {"nom": "SURPIQURE DOS + POSE COMPOSITION + OURLE BAS", "sam": 130, "archive": false},
  {"nom": "MONTAGE COL DOUBLURE", "sam": 100, "archive": false},
  {"nom": "0.1 EPAUL + COTE + DEVANT", "sam": 130, "archive": false},
  {"nom": "3 MANCHE", "sam": 0, "archive": false},
  {"nom": "MONTAGE COL + MANCHE", "sam": 0, "archive": false},
  {"nom": "SURPIQURE 0.1 MANCHE + OURLE MANCHE", "sam": 180, "archive": false},
  {"nom": "SURPIQURE  EPAUL +COTE + DEVANT", "sam": 135, "archive": false},
  {"nom": "MONTAGE DEVANT", "sam": 0, "archive": false},
  {"nom": "SURPIQURE COTE + POSE COMPOCITION", "sam": 0, "archive": false},
  {"nom": "ASSEMBLLAGE DOUBLURE DOS", "sam": 320, "archive": false},
  {"nom": "3 FIL PATTE + DOS + EPAUL + COTE", "sam": 180, "archive": false},
  {"nom": "PSE GREFFE", "sam": 95, "archive": false},
  {"nom": "RABATTAGE COL + PSE GREFFE", "sam": 0, "archive": false},
  {"nom": "FIXATION  TIKE", "sam": 20, "archive": false},
  {"nom": "PIQUAGE COL + RAZEZ PIED DE COL", "sam": 0, "archive": false},
  {"nom": "SURPIQURE 0.5 POIGNET + COUTURE ANGLASE MANCHE", "sam": 0, "archive": false},
  {"nom": "BIAIS DOS + BIAIS MANCHE", "sam": 100, "archive": false},
  {"nom": "SURPIQURE 0.1 DOS", "sam": 100, "archive": false},
  {"nom": "FRONCE DOS + FRONCE DEVANT", "sam": 100, "archive": false},
  {"nom": "NERVURE EMPIECEMENT +NERVURE EPAUL", "sam": 100, "archive": false},
  {"nom": "BIAIS DOS", "sam": 100, "archive": false},
  {"nom": "FRONCE DEVANT", "sam": 55, "archive": false},
  {"nom": "NERVURE EPAUL", "sam": 65, "archive": false},
  {"nom": "FIXATION PATTE MANCHE", "sam": 110, "archive": false},
  {"nom": "BIAIS COTE", "sam": 0, "archive": false},
  {"nom": "FRONCE COL + BAS MANCHE", "sam": 0, "archive": false},
  {"nom": "+NERVURE EPAUL", "sam": 65, "archive": false},
  {"nom": "SURPIQURE 0.1 COTE", "sam": 0, "archive": false},
  {"nom": "ASSEMBLLAGE EMPIECEMENT + PINCE DOS", "sam": 0, "archive": false},
  {"nom": "PLIS DOS + FRONCE", "sam": 0, "archive": false},
  {"nom": "BOU + MONTAGE PATTE", "sam": 0, "archive": false},
  {"nom": "0.1 COTE", "sam": 120, "archive": false},
  {"nom": "PLIS DOS", "sam": 120, "archive": false},
  {"nom": "BIAIS COL", "sam": 0, "archive": false},
  {"nom": "FIXATION PASSENT", "sam": 120, "archive": false},
  {"nom": "FIXATION PASSEN", "sam": 120, "archive": false},
  {"nom": "FRONCE", "sam": 50, "archive": false},
  {"nom": "BOU DEVANT", "sam": 0, "archive": false},
  {"nom": "PON DARE", "sam": 0, "archive": false},
  {"nom": "BIAIS COL + FIXATION PASON", "sam": 240, "archive": false},
  {"nom": "ASSEMBLLAGE MANCHE", "sam": 0, "archive": false},
  {"nom": "MONTAGE  DOS", "sam": 100, "archive": false},
  {"nom": "COUTUR ONGLAISE POCHE", "sam": 210, "archive": false},
  {"nom": "ASSEMBLLAGE POCHE + NERVURE", "sam": 240, "archive": false},
  {"nom": "MONTAGE EPAUL + COTE", "sam": 230, "archive": false},
  {"nom": "SURPIQURE COL + NERVURE", "sam": 125, "archive": false},
  {"nom": "BRA COTE", "sam": 0, "archive": false},
  {"nom": "3 FIL DOUBLURE", "sam": 0, "archive": false},
  {"nom": "BIAIS COTE + MANCHE", "sam": 0, "archive": false},
  {"nom": "FRONCE COL", "sam": 120, "archive": false},
  {"nom": "FIXATION PASSENT + 0.5 MANCHE", "sam": 0, "archive": false},
  {"nom": "0.5 EPAUL + COTE + DEVANT DOUBLURE", "sam": 0, "archive": false},
  {"nom": "0.5 MANCHE", "sam": 120, "archive": false},
  {"nom": "MONTAGE EPAUL + COTE +", "sam": 260, "archive": false},
  {"nom": "0NERVURE", "sam": 80, "archive": false},
  {"nom": "MONTAGE EPAUL + PON DARE POCHE", "sam": 1, "archive": false},
  {"nom": "MONTAGE  COTE", "sam": 0, "archive": false},
  {"nom": "MONTAGE MONCHE", "sam": 135, "archive": false},
  {"nom": "AASEMBLLAGE EMPIECEMENT", "sam": 120, "archive": false},
  {"nom": "BIAIS MANCHE + BIAIS COTE", "sam": 0, "archive": false},
  {"nom": "SUROIQURE 0.1 MANCHE", "sam": 0, "archive": false},
  {"nom": "SUROIQURE 0.1 COTE", "sam": 0, "archive": false},
  {"nom": "SURPIQURE 0.5 COTE", "sam": 0, "archive": false},
  {"nom": "SUROIQURE 0.1 MANCHE + PLIS MANCHE", "sam": 0, "archive": false},
  {"nom": "OURLES BAS", "sam": 0, "archive": false},
  {"nom": "FRONCE MANCHE", "sam": 0, "archive": false},
  {"nom": "OURLES BAS DOUBLURE", "sam": 0, "archive": false},
  {"nom": "POSE GREFFE + PANT DARE MANCHE + POSE COMPOCSITION", "sam": 0, "archive": false},
  {"nom": "MONTAGE PAIS COL + MANCHE", "sam": 0, "archive": false},
  {"nom": "3 FIL DOUBLURE EPAUL + COTE", "sam": 180, "archive": false},
  {"nom": "3 FIL POCHE + 3 FIL MILYE DEVANT DOUBLURE", "sam": 90, "archive": false},
  {"nom": "ASSEMBLLAGE BIAIS COL", "sam": 210, "archive": false},
  {"nom": "MONTAGE MILYE DEVANT", "sam": 100, "archive": false},
  {"nom": "BAIS BAS", "sam": 160, "archive": false},
  {"nom": "0.1 MANCHE + PLIS MANCHE", "sam": 150, "archive": false},
  {"nom": "BIAIS BAS", "sam": 0, "archive": false},
  {"nom": "ASSEMBLLAGE PIED CDE COL?", "sam": 60, "archive": false},
  {"nom": "0.1 MELYE DEVANT", "sam": 60, "archive": false},
  {"nom": "ASSEMBLLAGE DOUBLURE FERMETURE", "sam": 0, "archive": false},
  {"nom": "ASSEMBLLAGE DOUBLURE COL", "sam": 0, "archive": false},
  {"nom": "OURLE + FIXATION MANCHE", "sam": 0, "archive": false},
  {"nom": "RAZEZ BAS", "sam": 65, "archive": false},
  {"nom": "3 FOL COTE", "sam": 150, "archive": false},
  {"nom": "FRONCE BAS", "sam": 0, "archive": false},
  {"nom": "FIXATION TIKE + POSE COMPOSITION", "sam": 100, "archive": false},
  {"nom": "MARPUAGE + POSE GREFFE +CLASSAGE BONDE", "sam": 0, "archive": false},
  {"nom": "CLASSAGE BONDE TAILLE", "sam": 0, "archive": false},
  {"nom": "MONTAGE BONDE TAILLE", "sam": 0, "archive": false},
  {"nom": "AZERZ", "sam": 60, "archive": false},
  {"nom": "MONTAGE MANCHE + DOS", "sam": 280, "archive": false},
  {"nom": "NERVURE MANCHE + DOS", "sam": 170, "archive": false},
  {"nom": "MONTAGE BAS AVEC DOUBLURE", "sam": 0, "archive": false},
  {"nom": "3 FIL MILYE DEVANT DOUBLURE", "sam": 60, "archive": false},
  {"nom": "POSE GREFFE + 0.1 MELYE DEVANT", "sam": 0, "archive": false},
  {"nom": "MONTAGE BOU BIAIS", "sam": 110, "archive": false},
  {"nom": "CLASSAGE BONDE", "sam": 40, "archive": false},
  {"nom": "GREFFE +CLASSAGE BONDE", "sam": 40, "archive": false},
  {"nom": "MONTAGE PATTE + BIAIS", "sam": 130, "archive": false},
  {"nom": "RABATTAGE PATTE", "sam": 170, "archive": false},
  {"nom": "PLIS COL", "sam": 100, "archive": false},
  {"nom": "3 FIL BAS + 3 FIL COTE", "sam": 0, "archive": false},
  {"nom": "FIL COTE", "sam": 65, "archive": false},
  {"nom": "OURLE BAS +MANCHE", "sam": 0, "archive": false},
  {"nom": "MARPUAGE PLIS COL", "sam": 160, "archive": false},
  {"nom": "OURLES BAS MANCHE", "sam": 105, "archive": false},
  {"nom": "MONTAGE MILIEU DOS", "sam": 0, "archive": false},
  {"nom": "OURLE BAS + MANCHE", "sam": 0, "archive": false},
  {"nom": "3 FIL MILIEU DOS + EPAUL + COTE", "sam": 200, "archive": false},
  {"nom": "+ 3 FIL COTE", "sam": 75, "archive": false},
  {"nom": "3 FIL MILIEU DOS + COTE", "sam": 190, "archive": false},
  {"nom": "PAN DARE MANCHE", "sam": 0, "archive": false},
  {"nom": "0.1 MANCHE + MANTAGE COTE", "sam": 0, "archive": false},
  {"nom": "BAS MANCHE", "sam": 70, "archive": false},
  {"nom": "BAIS COTE", "sam": 0, "archive": false},
  {"nom": "MONTAGE DOS + MANCHE", "sam": 220, "archive": false},
  {"nom": "MONTAGE MNCHE + BAS", "sam": 220, "archive": false},
  {"nom": "0.1 MILIEU DOS + POSE GREFFE", "sam": 160, "archive": false},
  {"nom": "0.1 EPAUL + COTE + POSE COMPOSITION", "sam": 160, "archive": false},
  {"nom": "0.1 MANCHE + CLASSAGE COTE", "sam": 0, "archive": false},
  {"nom": "0.5 VOULANT", "sam": 170, "archive": false},
  {"nom": "ASSEMBLLAGE DOS+ MANCHE", "sam": 200, "archive": false},
  {"nom": "OURLE MANCHE DOUBLURE + PAN DARE", "sam": 0, "archive": false},
  {"nom": "MANTAGE + RABATTAGE POIGNET", "sam": 180, "archive": false},
  {"nom": "CHLASSAGE DOS", "sam": 200, "archive": false},
  {"nom": "MONTAGE BANDE TAILLE", "sam": 150, "archive": false},
  {"nom": "OULE BAS", "sam": 0, "archive": false},
  {"nom": "ASSEMBLLAGE COL  + NERVURE", "sam": 0, "archive": false},
  {"nom": "FIXATION PASON + MONTAGE ET RABATTAGE COL", "sam": 310, "archive": false},
  {"nom": "0.5 FOULANT", "sam": 0, "archive": false},
  {"nom": "ASSEMBLLAGE MANCHE + DOS", "sam": 180, "archive": false},
  {"nom": "ASSEMBLLAGE  DOS + MANCHAE", "sam": 180, "archive": false},
  {"nom": "RAZEZ + OURLE BAS DOUBLURE", "sam": 160, "archive": false},
  {"nom": "OURLE MANCHE DOUBLURE", "sam": 150, "archive": false},
  {"nom": "MONTAGE ET RABATTAGE PATTE DEVANT", "sam": 190, "archive": false},
  {"nom": "FIXATION LASTIK TAILLE", "sam": 140, "archive": false},
  {"nom": "PIQUAGE COL + NERVURE + MARQUAGE", "sam": 95, "archive": false},
  {"nom": "FIXATION TASTIK", "sam": 140, "archive": false},
  {"nom": "FIXATION TASTIKE", "sam": 140, "archive": false},
  {"nom": "MONTAGE PONDE TAILLE", "sam": 150, "archive": false},
  {"nom": "3 FIL BAS + FIXATION LASTIKE", "sam": 0, "archive": false},
  {"nom": "FIXATION LASTIKE", "sam": 50, "archive": false},
  {"nom": "ASSEMBLLAGE EMPIECEMENT + NARVURE", "sam": 140, "archive": false},
  {"nom": "RITOUCH", "sam": 85, "archive": false},
  {"nom": "ASSEMBLLAGE BOUBLURE COL", "sam": 130, "archive": false},
  {"nom": "RICOPAJE", "sam": 80, "archive": false},
  {"nom": "FIXATION BONDE", "sam": 20, "archive": false},
  {"nom": "MONTAGE DOUBLURE TAILLE 195", "sam": 200, "archive": false},
  {"nom": "MONTAGE MANCHE + BIAIS MANCHE", "sam": 0, "archive": false},
  {"nom": "POSE COMPOSITION", "sam": 75, "archive": false},
  {"nom": "POSE GREFFE +CLASSAGE BONDE", "sam": 60, "archive": false},
  {"nom": "FIXATION PONDE", "sam": 20, "archive": false},
  {"nom": "PLIS VOULANT", "sam": 0, "archive": false},
  {"nom": "0.5 OURLE BAS", "sam": 190, "archive": false},
  {"nom": "POSEFFE +CLASSAGE BONDE", "sam": 20, "archive": false},
];
